server:
  port: 8761
spring:
  application:
    name: eureka-server

#\u5355\u673A
#eureka:
#  instance:
#    hostname: localhost #\u4E3B\u673A\u540D
#  client:
#    # \u662F\u5426\u5C06\u81EA\u5DF1\u6CE8\u518C\u5230\u6CE8\u518C\u4E2D\u5FC3,\u9ED8\u8BA4\u4E3Atrue
#    register-with-eureka: false
#    # \u662F\u5426\u4ECE\u6CE8\u518C\u4E2D\u5FC3\u83B7\u53D6\u670D\u52A1\u6CE8\u518C\u4FE1\u606F \u9ED8\u8BA4\u4E3Atrue
#    fetch-registry: false
#    service-url:
#      #\u6CE8\u518C\u4E2D\u5FC3\u5BF9\u5916\u66B4\u9732\u7684\u6CE8\u518C\u5730\u5740
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

eureka:
  instance:
    hostname: eureka01 #\u4E3B\u673A\u540D
    prefer-ip-address: true #\u662F\u5426\u4F7F\u7528ip\u5730\u5740\u6CE8\u518C
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    #\u8BBE\u7F6E\u670D\u52A1\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740,\u6307\u5411\u53E6\u4E00\u4E2A\u6CE8\u518C\u4E2D\u5FC3
    service-url:
      defaultZone: http://localhost:8762/eureka/
