server:
  port: 8762
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: eureka02 #\u4E3B\u673A\u540D
    prefer-ip-address: true #\u662F\u5426\u4F7F\u7528ip\u5730\u5740\u6CE8\u518C
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    #\u8BBE\u7F6E\u670D\u52A1\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740,\u6307\u5411\u53E6\u4E00\u4E2A\u6CE8\u518C\u4E2D\u5FC3
    service-url:
      defaultZone: http://localhost:8761/eureka/
